version: "2"
services:
  # mysql settings
  db:
    image: mysql:5.7
    ports:
        - 3000:3306
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wp
       MYSQL_USER: root
       MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  # Wordpress settings
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    depends_on:
      - db
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: wp
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
    volumes:
      - ./themes:/var/www/html/wp-content/themes
  # phpmyadmin settings
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions
volumes:
  db-data: